---
- hosts: all 
  gather_facts: true
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - import_role:
        name: common
    - import_role:
        name: workstations
      when: "'workstations' in group_names"
      
