---
- hosts: all
  gather_facts: true
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - import_role:
        name: gnome
      when: "'gnome' in group_names"
      
