- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Update Arch Linux
      pacman:
        update_cache: yes
        upgrade: yes
      when:
        - ansible_facts['distribution'] == "Archlinux"
    - name: Update APT packages
      apt:
        upgrade: dist
        update_cache: yes
        autoclean: yes
      when:
        - ansible_facts['distribution'] == "Ubuntu"
