---
- name: Ensure dependencies are installed.
  package: 
    name: 
    - bash
    - curl
    - wget
    - rsync
    - gzip
    - fail2ban
    state: present

- include_tasks: setup-Common-Arch.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: setup-Common-Debian.yml
  when: ansible_os_family == 'Debian'


