---
- name: Ensure dependencies are installed.
  package: name=curl state=present
  
- include_tasks: setup-Common.yml
  
- include_tasks: setup-Arch.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

