- name: Install pacman config
  template:
    dest: /etc/pacman.conf
    group: root
    mode: 0644
    owner: root
    src: pacman.conf.j2
- name: Disable BTRFS quotas & chattr + C for VM / Container directories
  shell: btrfs quota disable / && chattr +C /var/lib/machines && chattr +C /var/lib/libvirt
- name: Update package cache
  pacman:
    update_cache: yes
- name: Create drop-in directories for systemd configuration
  file:
    group: root
    mode: 0755
    owner: root
    path: /etc/systemd/{{ item }}
    state: directory
  loop:
    - system/getty@tty1.service.d
    - journald.conf.d
- name: Install journald.conf overrides
  template:
    dest: /etc/{{ item.path }}
    group: root
    mode: 0644
    owner: root
    src: "{{ item.conf }}"
  notify:
    - restart journald
  loop:
    - {
        conf: "journald.conf.j2",
        path: "/systemd/journald.conf.d/override.conf",
      }
    - {
        conf: "getty.conf",
        path: "/systemd/system/getty@tty1.service.d/override.conf",
      }
    - { conf: "makepkg.conf", path: "makepkg.conf" }
- name: Enable systemd-oomd
  systemd:
    name: systemd-oomd
    state: started
    enabled: yes
- name: Install user configurations
  copy:
    dest: /home/nico/{{ item.path }}
    group: nico
    mode: 0644
    owner: nico
    src: "{{ item.conf }}"
  loop:
    - { conf: ".gitconfig", path: ".gitconfig" }
    - { conf: "modprobed.db", path: ".config/modprobed.db" }
    - { conf: "starship.toml", path: ".config/starship.toml" }
- name: Copy user directories
  copy:
    dest: "{{ item.path }}"
    follow: yes
    group: nico
    mode: 0644
    owner: nico
    src: "{{ item.conf }}"
  loop:
    - { conf: "autostart/", path: "/home/nico/.config/autostart/" }
    - { conf: "applications/", path: "/home/nico/.local/share/applications/" }
- name: Copy system directories
  copy:
    dest: "{{ item.path }}"
    follow: yes
    group: root
    mode: 0644
    owner: root
    src: "{{ item.conf }}"
  loop:
    - { conf: "nspawn/", path: "/etc/nspawn/" }
    - { conf: "applications/", path: "/home/nico/.local/share/applications/" }
- name: Update packages to the latest version
  pacman:
    update_cache: yes
    upgrade: yes
- name: Disable unused Systemd services
  systemd:
    name: "{{ item }}"
    enabled: no
  loop:
    - ModemManager
    - bluetooth-autoconnect
    - remote-fs.target
- name: Mask unwanted Systemd services
  systemd:
    name: "{{ item }}"
    enabled: no
    masked: yes
  loop:
    - lvm2-lvmpolld
    - lvm2-lvmpolld.socket
    - lvm2-monitor
- name: Enable Systemd system services
  systemd:
    name: "{{ item }}"
    state: started
  loop:
    - ananicy-cpp
    - hblock.timer
    - ufw
- name: Create directory for config.fish
  file:
    group: nico
    mode: 0755
    owner: nico
    path: /home/nico/.config/fish/
    state: directory
- name: Install fish configuration
  copy:
    dest: /home/nico/.config/fish/
    group: nico
    mode: 0644
    owner: nico
    src: config.fish
